apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: devops-ca-2
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP

