apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-ca-2
type: Opaque
stringData:
  GROQ_API_KEY: "replace-me"
  MONGO_URI: "mongodb://mongo:27017/devops"
  MONGO_DB_NAME: "devops"
  MONGO_COLLECTION_NAME: "logs"

