name: CD - Vercel Deployment (Next.js)

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} \
          --build-env NODE_ENV=production \
          --scope=${{ secrets.VERCEL_SCOPE }} \
          --confirm

      - name: Deployment Status
        if: success()
        run: |
          echo "✅ Deployment to Vercel completed successfully!"
          echo "URL: https://${{ secrets.VERCEL_PROJECT_ID }}.vercel.app"
      - name: Deployment Failed
        if: failure()
        run: |
          echo "❌ Deployment failed. Check the logs for more details."
