name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend - Install, Lint, Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

  backend:
    name: Backend - Install, Lint, Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chatbot-backend
    env:
      BACKEND_EAGER_INIT: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 . || true

      - name: Type check (mypy)
        run: |
          pip install mypy
          mypy . || true

      - name: Basic import test
        run: |
          python -c "import app; import app.main"

  docker-build:
    name: Docker Build - Frontend and Backend
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/devops-ca-2-frontend:ci

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./chatbot-backend
          file: ./chatbot-backend/Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/devops-ca-2-backend:ci



